### ISSUE TITLE
stack.availability_zones fails if exclude_availability_zones not set in Cloudfile

### ISSUE THREAD

**Issue by athompson-r7** [rapid7/convection#234]
# Description

For some reason [@exclude_availability_zones](https://github.com/rapid7/convection/blob/master/lib/convection/control/stack.rb#L112) if defaulting to `nil` even though we set the default to an empty Array.

This was introduced in #232 

## Expected behavior

`@exclude_availability_zones` should default to an empty Array if it is not specified in the Cloudfile.

## Observed behavior

The following exception is thrown because `@exclude_availability_zones` is defaulting to `nil` not an empty Array.

## Steps to Reproduce

Install version 1.0.4 of the gem and run `convection diff` on a stack that includes and the Cloudfile does **not** include `exclude_availability_zones`:
```
stack.availability_zones do
  # something
end
```

# Stack Trace or Log Messages

<details>
<summary>Stack trace for `brief error context`</summary>
<pre>
.../convection-1.0.4/lib/convection/control/stack.rb:441:in `availability_zones': undefined method `empty?' for nil:NilClass (NoMethodError)
.../templates/ec2/vpc.rb:132:in `block (2 levels) in <module:EC2>'
.../convection-1.0.4/lib/convection/model/template.rb:23:in `instance_exec'
...snip...
</pre>
</details>

**Comment by erran-r7** [comment]
Resolved in #235.
